### PR TITLE
Changes required to complete a build against Pentaho 5.1 or trunk as requested in #121

### PR DESCRIPTION
**Pull request by pietercvdm**
Applied Pentaho repository fixes, fixed PostgreSQL dependency and updated project to build against Pentaho 5.1.  The commits are separated so it can be cherry-picked to other branches if you want to build against older versions of OpenERP/Pentaho.

### CODE REVIEW

**Comment by flotho** [comment]
I vote for this !

**Comment by nono66** [comment]
I vote for this !

**Comment by flotho** [comment]
Is it also possible to push this in the 7.0 branch?

**Comment by richard-willdooit** [comment]
@flotho 

I will look at it, but it will not be this week.  If you wish to submit a pull request, it will probably happen sooner ;)

**Comment by pietercvdm** [comment]
@flotho Give my version70 branch a go here: https://github.com/pietercvdm/Pentaho-reports-for-OpenERP.git.

I have also created a pull request to merge the changes in.

**Comment by richard-willdooit** [comment]
All merged.  Also, as commented on another thread, the pre-built war file is available for download: http://cloud1.willowit.com.au/dist/pentaho-reports-for-openerp.war

**Pull request merged**
