### PR TITLE
Updated to use Pentaho 5.3

### PR DESCRIPTION
**Pull request by pietercvdm**
Hi Guys

Please give it a test and let me know how it goes.

Kind Regards,
Pieter

### CODE REVIEW

**Comment by NMello** [comment]
I have tried,but i get this error:
2015-04-13 10:35:45,999 7501 ERROR odoo openerp.http: Exception during
JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 567, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 300, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 796, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 396, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line
949, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line
941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr,
request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/pentaho_reports/wizard/report_prompt.py",
line 361, in fields_view_get
    parameters = self._setup_parameters(cr, uid, report_action_id,
context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/addons/pentaho_reports/wizard/report_prompt.py",
line 199, in _setup_parameters
    report_parameters = proxy.report.getParameterInfo(proxy_argument)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
Fault: <Fault 0: 'Failed to invoke method getParameterInfo in class
com.willowit.reporting.PentahoRenderer: Unable to parse the document:
ResourceKey{schema=org.pentaho.reporting.libraries.docbundle.bundleloader.ZipResourceBundleLoader,
identifier=content.xml,
factoryParameters={org.pentaho.reporting.libraries.resourceloader.FactoryParameterKey{name=repository}=org.pentaho.reporting.libraries.repository.zipreader.ZipReadRepository@eb3a3c,
org.pentaho.reporting.libraries.resourceloader.FactoryParameterKey{name=repository-loader}=org.pentaho.reporting.libraries.docbundle.bundleloader.ZipResourceBundleLoader@100831},
parent=ResourceKey{schema=org.pentaho.reporting.libraries.resourceloader.loader.raw.RawResourceLoader,
identifier=[B@1523841, factoryParameters={}, parent=null}}'>

with Pentaho 5.2 reports it works fine.

**Comment by pietercvdm** [comment]
Thanks.  The stacktrace doesn't point to anything obvious.  Nothing from a Pentaho-to-OpenERP should have changed, only the designer (ie. the underlying communication API stayed the same).  I'll have to build a system and check it out but won't have time this week or the next.  I can only get to it after the 27th.

**Comment by richard-willdooit** [comment]
@pietercvdm @NMello I have just tested and had no issue.  5.3 report failed on 5.2 instance and succeeded on 5.3 build.  5.3 war file updated appropriately.

**Comment by pietercvdm** [comment]
Great, thanks for following it up @richard-willowit.  I'll consider this issue resolved then.  Let me know if you find anything else.

**Pull request merged**
