### PR TITLE
[FIX] XMLRPC localhost issue with version 7

### PR DESCRIPTION
**Pull request by andreschenkels**
If you want to run OpenERP and the Pentaho Report Server on 2 different servers you can have a problem with the dependicie of the pentaho openerp module on the XMLRPC interface setting of the OpenERP config. 
In the case you have more as 1 interface you need to set it to empty. If this value is empty the Pentaho Server will comunicate back to localhost and there will be no OpenERP server in this case.
This FIX will provide you extra system parameters to set the XMLRPC interface.

### CODE REVIEW

**Comment by lxdorney** [comment]
Hi, is there any bug for Pentaho-reports-for-OpenERP after I installed pentaho-reports I can't see under Settings/Actions the sub menu of Pentaho Reports. is there any missed configuration?
I successfully installed addons with no errors.

I don't know if this is the right link to post this issue

Im using OpenERP 7

thanks

**Comment by flotho** [comment]
Hy,

There is no more submenu.
You can manage your pentaho reports in the actions> reports menu and set a report as a pentaho report thanks to the latest evolutions of the module.

regards

**Comment by lxdorney** [comment]
I have a table name "product" with the following fields: date, name,
description, price, qty, return, delivery, pullout and offtake.
I need to generate weekly report of my product:

Here is the weekly report and formula that we need to generate in pentaho
report openerp
for the periods 1-7/6/2014 is first week of the monthly
TOTAL DELIVERY = SUM OF DELIVERYs from ie. june 1 to 7

TOTAL RETURN = SUM OF RETURNs from june 1 to 7
TOTAL OFFTAKE = (BEG. WAREHOUSE + SELLING AREA) + (TOTAL DELIVERY + TOTAL
RETURN)-(END. WAREHOUSE + SELLING AREA)-TOTAL PULL-OUT

WEEKLY SALES = PRICE \* TOTAL OFFTAKE

to generate the second week need minus the TOTAL OFFTAKE of the first week
for the periods 8-14/6/2014 which is the second week of the monthly
TOTAL DELIVERY = SUM OF DELIVERYs from ie. june 1 to 7

TOTAL RETURN = SUM OF RETURNs from june 1 to 7
TOTAL OFFTAKE = (BEG. WAREHOUSE + SELLING AREA) + (TOTAL DELIVERY + TOTAL
RETURN)-(END. WAREHOUSE + SELLING AREA)-TOTAL PULL-OUT

WEEKLY SALES = PRICE \* TOTAL OFFTAKE

Can pentaho report openerp handle this?
for short the total of secondweek = totalsecondweek - totalfirstweek.

Thanks

**Comment by lxdorney** [comment]
Hi Expert,

My Apologies,
I dont know if this is the right to Post my question
I have a table name "product" with the following fields: date, name,
description, price, qty, return, delivery, pullout and offtake.
I need to generate weekly report of my product:

Here is the weekly report and formula that we need to generate in pentaho
report openerp
for the periods 1-7/6/2014 is first week of the monthly
TOTAL DELIVERY = SUM OF DELIVERYs from ie. june 1 to 7

TOTAL RETURN = SUM OF RETURNs from june 1 to 7
TOTAL OFFTAKE = (BEG. WAREHOUSE + SELLING AREA) + (TOTAL DELIVERY + TOTAL
RETURN)-(END. WAREHOUSE + SELLING AREA)-TOTAL PULL-OUT

WEEKLY SALES = PRICE \* TOTAL OFFTAKE

to generate the second week need minus the TOTAL OFFTAKE of the first week
for the periods 8-14/6/2014 which is the second week of the monthly
TOTAL DELIVERY = SUM OF DELIVERYs from ie. june 1 to 7

TOTAL RETURN = SUM OF RETURNs from june 1 to 7
TOTAL OFFTAKE = (BEG. WAREHOUSE + SELLING AREA) + (TOTAL DELIVERY + TOTAL
RETURN)-(END. WAREHOUSE + SELLING AREA)-TOTAL PULL-OUT

WEEKLY SALES = PRICE \* TOTAL OFFTAKE

Can pentaho report openerp handle this?
for short the total of secondweek = totalsecondweek - totalfirstweek.

Thanks

On Thu, May 22, 2014 at 6:36 AM, Richard deMeester <notifications@github.com

> wrote:
> 
> Closed #114
> https://github.com/WillowIT/Pentaho-reports-for-OpenERP/issues/114.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WillowIT/Pentaho-reports-for-OpenERP/issues/114#event-123582147
> .

**Comment by richard-willdooit** [comment]
@lxdorney - This was lost you posted on a closed issue.  If you still want an answer, please create a new issue for it.  Without looking in detail, it is the sort of thing the Pentaho module can easily handle.

**Pull request merged**
